name: 'GitArmor Action'
description: 'GitHub Action that runs GitArmor against your GitHub repo and org to check against security policy that you have defined.'
branding:
  color: blue
  icon: unlock
inputs:
  repo:
    description: 'Repository name'
    required: true
  org:
    description: 'Organization name'
    required: true
  token:
    description: 'GitHub Token (GITHUB_TOKEN) with admin access to the repository/organization'
    required: true
  level:
    description: 'Level on which to run GitArmor - repository or organization'
    required: true
  policy-dir:
    description: 'Location of the directory containing the policies'
    required: true
outputs:
  check-results-json:
    description: 'Results of the GitArmor check in JSON format'
  check-results-text:
    description: 'Results of the GitArmor check in Markdown format'
runs:
  using: 'node20'
  main: 'dist/index.js'
